"""Live event bus, granular log records and thread-safe statistics.

Every internal decision the engine makes — wildcard checks, OSINT fetches, DNS
requests, TCP probes, HTTP verifications, filter drops and network errors — is
emitted as a :class:`ScanEvent` onto the :class:`EventBus`.  The bus is safe to
write to from any number of concurrent asyncio tasks *and* from a foreign
thread (the engine runs in its own event loop while the TUI polls on the main
thread), which is what makes the live deep-logging requirement work.
"""

from __future__ import annotations

import asyncio
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Iterable

# --------------------------------------------------------------------------- #
# Events
# --------------------------------------------------------------------------- #

SEVERITY_ORDER = (
    "trace",
    "debug",
    "info",
    "notice",
    "success",
    "warn",
    "error",
    "critical",
)


@dataclass(slots=True)
class ScanEvent:
    """One granular internal event streamed to the interface."""

    seq: int
    ts: float
    severity: str
    category: str
    message: str
    host: str | None = None
    port: int | None = None
    ip: str | None = None
    url: str | None = None
    data: dict[str, Any] = field(default_factory=dict)

    @property
    def clock(self) -> str:
        """``HH:MM:SS.mmm`` wall-clock stamp for the live console."""
        lt = time.localtime(self.ts)
        return (
            f"{lt.tm_hour:02d}:{lt.tm_min:02d}:{lt.tm_sec:02d}."
            f"{int((self.ts % 1) * 1000):03d}"
        )

    def render(self) -> str:
        """Plain one-line rendering (no colour)."""
        tag = f"[{self.category or self.severity}]".ljust(11)
        target = ""
        if self.host:
            target = f" {self.host}"
            if self.port:
                target += f":{self.port}"
        return f"{self.clock} {tag}{target} {self.message}"

    def to_dict(self) -> dict[str, Any]:
        return {
            "seq": self.seq,
            "ts": self.ts,
            "clock": self.clock,
            "severity": self.severity,
            "category": self.category,
            "message": self.message,
            "host": self.host,
            "port": self.port,
            "ip": self.ip,
            "url": self.url,
            "data": self.data,
        }


# --------------------------------------------------------------------------- #
# Thread-safe statistics
# --------------------------------------------------------------------------- #


@dataclass
class Stats:
    """Aggregate counters shown on the live statistics panel."""

    started_at: float = field(default_factory=time.time)
    finished_at: float | None = None
    phase: str = "init"
    candidates: int = 0          # subdomains queued for DNS
    osint_unique: int = 0        # unique hosts harvested from OSINT
    brute_unique: int = 0        # unique hosts generated by the wordlist
    dns_queries: int = 0
    dns_resolved: int = 0
    dns_failed: int = 0
    dns_cache_hits: int = 0
    ipv6_hosts: int = 0
    dns_confirmed: int = 0
    dns_unconfirmed: int = 0
    wildcard_hits: int = 0
    wildcard_filtered: int = 0
    #: Hosts left unscanned because they live on third-party infrastructure.
    provider_skipped: int = 0
    #: Findings merged from a previous report of the same domain.
    carried_over: int = 0
    ports_probed: int = 0
    ports_open: int = 0
    http_probes: int = 0
    filtered_no_web: int = 0
    findings: int = 0
    errors: int = 0
    timeouts: int = 0
    sources: dict[str, int] = field(default_factory=dict)
    active_tasks: int = 0
    #: Phase-aware progress.  The engine sets ``progress_total``/``progress_done``
    #: as the scan moves from resolution to the port sweep, so the bar tracks the
    #: *whole* run instead of sitting at 100 % after DNS finished.
    progress_total: int = 0
    progress_done: int = 0

    # -- derived ---------------------------------------------------------- #
    @property
    def elapsed(self) -> float:
        end = self.finished_at if self.finished_at is not None else time.time()
        return max(0.0, end - self.started_at)

    @property
    def hosts_per_second(self) -> float:
        elapsed = self.elapsed
        return (self.dns_queries / elapsed) if elapsed > 0 else 0.0

    @property
    def progress(self) -> float:
        if self.progress_total > 0:
            return min(1.0, self.progress_done / self.progress_total)
        if not self.candidates:
            return 0.0
        done = self.dns_resolved + self.dns_failed
        return min(1.0, done / self.candidates)

    def set_progress(self, done: int, total: int) -> None:
        """Set the phase-aware progress counters (total 0 = fall back to DNS)."""
        self.progress_done = max(0, int(done))
        self.progress_total = max(0, int(total))

    def snapshot(self) -> dict[str, Any]:
        return {
            "phase": self.phase,
            "elapsed": round(self.elapsed, 2),
            "candidates": self.candidates,
            "osint_unique": self.osint_unique,
            "brute_unique": self.brute_unique,
            "dns_queries": self.dns_queries,
            "dns_resolved": self.dns_resolved,
            "dns_failed": self.dns_failed,
            "dns_cache_hits": self.dns_cache_hits,
            "progress": round(self.progress, 4),
            "ipv6_hosts": self.ipv6_hosts,
            "dns_confirmed": self.dns_confirmed,
            "dns_unconfirmed": self.dns_unconfirmed,
            "wildcard_hits": self.wildcard_hits,
            "wildcard_filtered": self.wildcard_filtered,
            "provider_skipped": self.provider_skipped,
            "carried_over": self.carried_over,
            "ports_probed": self.ports_probed,
            "ports_open": self.ports_open,
            "http_probes": self.http_probes,
            "filtered_no_web": self.filtered_no_web,
            "findings": self.findings,
            "errors": self.errors,
            "timeouts": self.timeouts,
            "sources": dict(self.sources),
            "rate": round(self.hosts_per_second, 1),
            "active_tasks": self.active_tasks,
        }


# --------------------------------------------------------------------------- #
# Event bus
# --------------------------------------------------------------------------- #


class EventBus:
    """Fan-out sink for :class:`ScanEvent` objects.

    * ``emit()`` is callable from any thread / coroutine.
    * ``drain()`` hands the pending events to a polling UI (TUI, dashboard).
    * ``stream()`` yields events to asyncio consumers (headless console).
    """

    def __init__(self, *, history: int = 20_000, live_buffer: int = 20_000) -> None:
        self._lock = threading.RLock()
        self._seq = 0
        self._pending: Deque[ScanEvent] = deque(maxlen=live_buffer)
        self._history: Deque[ScanEvent] = deque(maxlen=history)
        self._queue: asyncio.Queue[ScanEvent] | None = None
        self._queue_loop: asyncio.AbstractEventLoop | None = None
        self.stats = Stats()
        #: Events below this severity (index into :data:`SEVERITY_ORDER`) are
        #: dropped at the source — no ``ScanEvent`` is allocated or buffered.
        #: ``0`` (trace) keeps everything.
        self.min_severity = 0
        #: Events dropped because a streaming consumer could not keep up.
        self.dropped = 0

    # -- production ------------------------------------------------------- #
    def emit(
        self,
        message: str,
        severity: str = "info",
        category: str = "info",
        *,
        host: str | None = None,
        port: int | None = None,
        ip: str | None = None,
        url: str | None = None,
        **data: Any,
    ) -> ScanEvent:
        if self.min_severity > 0:
            rank = SEVERITY_ORDER.index(severity) if severity in SEVERITY_ORDER else 0
            if rank < self.min_severity:
                # Never allocate or buffer an event the consumer will not show.
                return None  # type: ignore[return-value]
        with self._lock:
            self._seq += 1
            event = ScanEvent(
                seq=self._seq,
                ts=time.time(),
                severity=severity,
                category=category,
                message=message,
                host=host,
                port=port,
                ip=ip,
                url=url,
                data=data,
            )
            self._pending.append(event)
            self._history.append(event)
            if category == "phase":
                # Regression: ``phase`` used to live only inside the event, so
                # every snapshot reported the initial value forever while the
                # dashboard showed "phase: init" during a running scan.
                self.stats.phase = message
            queue = self._queue
            loop = self._queue_loop
        if queue is not None and loop is not None and not loop.is_closed():
            try:
                loop.call_soon_threadsafe(self._offer, queue, event)
            except RuntimeError:  # pragma: no cover - loop shut down mid-emit
                pass
        return event

    def _offer(self, queue: asyncio.Queue[ScanEvent], event: ScanEvent) -> None:
        """Hand one event to a streaming consumer, dropping it if it is full.

        ``put_nowait`` on a full bounded queue raises ``QueueFull`` *inside* the
        loop callback, which would surface as an unhandled exception in the event
        loop rather than as a dropped log line.
        """
        try:
            queue.put_nowait(event)
        except asyncio.QueueFull:
            self.dropped += 1

    # -- consumption ------------------------------------------------------ #
    def drain(self, limit: int = 500) -> list[ScanEvent]:
        """Pop up to *limit* pending events (oldest first)."""
        out: list[ScanEvent] = []
        with self._lock:
            while self._pending and len(out) < limit:
                out.append(self._pending.popleft())
        return out

    def history(self, *, limit: int | None = None) -> list[ScanEvent]:
        with self._lock:
            items = list(self._history)
        return items[-limit:] if limit else items

    def attach_queue(self, loop: asyncio.AbstractEventLoop) -> asyncio.Queue[ScanEvent]:
        """Register the asyncio queue used by :meth:`stream`."""
        queue: asyncio.Queue[ScanEvent] = asyncio.Queue(maxsize=50_000)
        with self._lock:
            self._queue = queue
            self._queue_loop = loop
        return queue

    async def stream(self) -> Any:
        """Async generator over events (consumed by the headless renderer)."""
        queue = self.attach_queue(asyncio.get_running_loop())
        while True:
            event = await queue.get()
            if event.category == "__eof__":
                break
            yield event

    def close_stream(self) -> None:
        with self._lock:
            queue, loop = self._queue, self._queue_loop
            self._queue = None
        if queue is not None and loop is not None and not loop.is_closed():
            eof = ScanEvent(
                seq=-1, ts=time.time(), severity="info", category="__eof__", message="eof"
            )
            try:
                loop.call_soon_threadsafe(queue.put_nowait, eof)
            except RuntimeError:  # pragma: no cover
                pass

    def clear(self) -> None:
        """Forget every buffered event **and reset the statistics**.

        Called before each scan starts, so a second scan in the same process (a
        new TUI scan, a dashboard re-run) must not inherit the previous run's
        counters, phase or start time.
        """
        with self._lock:
            self._pending.clear()
            self._history.clear()
            self.stats = Stats()
            self.dropped = 0

    # -- statistics helpers ---------------------------------------------- #
    def set_verbosity(self, severity: str) -> None:
        """Drop events below *severity* at the source (e.g. ``"info"`` hides
        trace/debug).  ``"trace"`` restores the full stream."""
        key = str(severity).strip().lower()
        self.min_severity = SEVERITY_ORDER.index(key) if key in SEVERITY_ORDER else 0

    def bump(self, field_name: str, amount: int = 1) -> None:
        # Statistics counters are updated without the lock: a rare lost
        # increment under contention is imperceptible, while the lock was the
        # single hottest point of contention across the whole pipeline (every
        # DNS query and every port probe bumped at least one counter).
        setattr(self.stats, field_name, getattr(self.stats, field_name) + amount)

    def bump_clamped(self, field_name: str, amount: int = 1, *, minimum: int = 0) -> None:
        """Best-effort ``bump`` that never lets a counter fall below *minimum*."""
        current = getattr(self.stats, field_name)
        setattr(self.stats, field_name, max(minimum, current + amount))

    def bump_source(self, source: str, amount: int) -> None:
        self.stats.sources[source] = self.stats.sources.get(source, 0) + amount

    def set_field(self, field_name: str, value: Any) -> None:
        setattr(self.stats, field_name, value)

    def snapshot(self) -> dict[str, Any]:
        with self._lock:
            return self.stats.snapshot()

    # -- convenience emitters -------------------------------------------- #
    def phase(self, message: str) -> None:
        self.emit(message, "info", "phase")

    def wildcard(self, message: str, **kw: Any) -> None:
        self.emit(message, "warn", "wildcard", **kw)

    def osint(self, message: str, **kw: Any) -> None:
        self.emit(message, "info", "osint", **kw)

    def dns(self, message: str, **kw: Any) -> None:
        self.emit(message, "info", "dns", **kw)

    def port(self, message: str, **kw: Any) -> None:
        self.emit(message, "info", "port", **kw)

    def http(self, message: str, **kw: Any) -> None:
        self.emit(message, "info", "http", **kw)

    def probe(self, message: str, **kw: Any) -> None:
        self.emit(message, "success", "probe", **kw)

    def filtered(self, message: str, **kw: Any) -> None:
        self.emit(message, "debug", "filter", **kw)

    def error(self, message: str, **kw: Any) -> None:
        self.emit(message, "error", "error", **kw)

    def warn(self, message: str, **kw: Any) -> None:
        self.emit(message, "warn", "warn", **kw)


#: Process-wide default bus.
BUS = EventBus()


def format_events(events: Iterable[ScanEvent]) -> str:
    return "\n".join(event.render() for event in events)
